let mockEmployees = JSON.parse(localStorage.getItem("employees")) || [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    email: "john@example.com",
    department: "HR",
    role: "Manager",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    email: "jane@example.com",
    department: "Engineering",
    role: "Developer",
  },
  {
    id: 3,
    firstName: "Michael",
    lastName: "Brown",
    email: "michael@example.com",
    department: "Finance",
    role: "Analyst",
  },
  {
    id: 4,
    firstName: "Emily",
    lastName: "Davis",
    email: "emily@example.com",
    department: "Marketing",
    role: "Coordinator",
  },
  {
    id: 5,
    firstName: "David",
    lastName: "Wilson",
    email: "david@example.com",
    department: "Engineering",
    role: "Senior Developer",
  },
  {
    id: 6,
    firstName: "Sarah",
    lastName: "Taylor",
    email: "sarah@example.com",
    department: "HR",
    role: "Recruiter",
  },
  {
    id: 7,
    firstName: "James",
    lastName: "Anderson",
    email: "james@example.com",
    department: "Sales",
    role: "Account Executive",
  },
  {
    id: 8,
    firstName: "Laura",
    lastName: "Martinez",
    email: "laura@example.com",
    department: "Customer Support",
    role: "Support Specialist",
  },
  {
    id: 9,
    firstName: "Robert",
    lastName: "Thomas",
    email: "robert@example.com",
    department: "IT",
    role: "System Administrator",
  },
  {
    id: 10,
    firstName: "Lisa",
    lastName: "Jackson",
    email: "lisa@example.com",
    department: "Operations",
    role: "Operations Manager",
  },
];
